### ISSUE TITLE
Integration with ACT

### ISSUE THREAD

**Issue by byteslash** [zhyupe/FFXIV-Packet-Dissector#2]
Any chance you could convert this git to C# ? i am looking at ways to read ffxiv data from a console and i can see this does that on wireshark....but i dont know the first thing about lua.

**Comment by zhyupe** [comment]
In fact I have implemented an analyzer in C#, at [zhyupe/FFXIV-Packet-Analyzer](https://github.com/zhyupe/FFXIV-Packet-Analyzer). However it's really slow and would be obviously laggy after running a while. As I'm not a professional in C#, I have no idea how to optimize it. And it would take too much work to implement a binary viewer like Wireshark. So I moved to the plugin system of Wireshark. But you can use that repository to do the data dumping job or develop an ACT plugin.

**Comment by FairyScript** [comment]
I use [machina ](https://github.com/ravahn/machina) for data analysis in C# ,but machina lib does not provide the opcode.
